### ISSUE TITLE
Is the graph edit distance developmented?

### ISSUE THREAD

**Issue by nbl97** [jajupmochi/graphkit-learn#41]
How long will the edit distance be supported? Thanks a lot!

**Comment by jajupmochi** [comment]
Sorry for the delay.

There are two ways to compute graph edit distances with our library:

1. Use the `gedlib` module.

This module integrates a modified version of the [`gedlibpy`](https://github.com/Ryurin/gedlibpy) library, which is a Python interface of the [`modified version`](https://github.com/jajupmochi/gedlib) of the C++ library [`GEDLIB`](https://github.com/dbblumenthal/gedlib). The latter contains many state-of-the-art methods to compute GEDs. You can check its documentation for detail.

The following codes show an example to use this module:
```
from gklearn.gedlib import librariesImport
from gklearn.gedlib.gedlibpy import GEDEnv

ged_env = GEDEnv() # Initailize GED environment.
ged_env.set_edit_cost(’CONSTANT’, # Edit cost function.
    edit _cost_c onstants = [3, 3, 1, 3, 3, 1] # The constant edit costs.
ged_env.add_nx_graph(graph1, ’’) # Add graph1.
ged_env.add_nx_graph(graph2, ’’) # Add graph2.
listID = ged_env.get_all_graph_ids() # Get list IDs of graphs.
ged_env.init() # Initialize the GED environment.
ged_env.set_method(’BIPARTITE’), # Set GED method.
ged_env.init_method() # Initialize the GED method.
ged_env.run_method(listID[0], listID[1]) # Run method.

pi_forward = ged_env.get_forward_map(listID[0], listID[1]) # Get the forward map.
pi_backward = ged_env.get_backward_map(listID[0], listID[1]) # Get the backward map.
dis = ged_env.get_upper_bound(listID[0], listID[1]) # Get the GED between two graphs.
```

If you are using Python 3.6 on Ubuntu OS, you should be able to run this directly. Otherwise, you will need to compile the [`gedlibpy`](https://github.com/jajupmochi/gedlib) library (the modified version) first with the following steps:
-  Download the [`include`](https://github.com/Ryurin/gedlibpy/tree/master/include) folder and put it in the `gedlib` module.
- Replace the content in the `include/gedlib-master` folder with the content of [the modified version of `GEDLIB`](https://github.com/jajupmochi/gedlib).
- Compile the library following the instruction in the `README.rst` file in the `gedlib` module.

2. Use `ged` module.

We implemented a part of the `GEDLIB` library in pure Python under the `ged` module. You can use the aforementioned codes to use this module, by simply replacing the import lines with the following statement:
```
from gklearn.ged.env import GEDEnv
```

For now, we have implemented the Bipartite method and the corresponding LSAPE-GED paradigm (see [this paper](https://link.springer.com/article/10.1007/s00778-019-00544-1) for detail). Unfortunately, I am busy preparing for my Ph.D. defense lately so I may not have enough time to expand it. I will see what to do after. You are welcome to submit your implementation if interested.

Please let me know if you have any problems. Thanks for your attention to our library.
